### ISSUE TITLE
SampleRate

### ISSUE THREAD

**Issue by borbysh** [FrancescoBonicelli/SDRSharp.Plugin.SignalRecorder#1]
Hi! I've got 37500 samples per second in the recorded data file, while my rtl-sdr dongle is set up at 2.4 MSPS. Could you please advise something to get the maximal possible time resolution?
Regards
Alex

**Comment by FrancescoBonicelli** [comment]
Hi Alex. Thank you for using my plugin!
After investigating about your report I found that the number of samples saved is based on the requested saving time and the sample rate (the bandwidth and not the sdr sample rate). You can find the bandwidth setting in the Radio panel.

**Comment by borbysh** [comment]
Dear Francesco,
Thank you very much for your reply! It works indeed. If so, it looks like
the raw data from the dongle undergo DFT, then we take a certain part of
the spectrum, defined by the bandwidth value, and then make the inverse DFT
to return to the time domain. A bit tricky, imho.
Couldn't you suggest a way to access the raw I/Q data from the dongle
directly?
Regards
Alex
